data:
  data_directory: /Users/zakharca/Documents/Study/thesis/data
  creds:
    flickr:
      key: '875624e8b45c9b1458315b4d18ebabbd'
      secret: '8ebf43cd9cfd3e7e'
  db:
    host: localhost
    port: 51998
    database: im2gps
  datasets:
    split_file: 'resources/datasets.json'
    train: descriptors/512_flickr_descriptor_train.h5
    train_queries: descriptors/512_flickr_descriptor_train_q.h5
    test_queries: descriptors/512_flickr_descriptor_test_q.h5
    validation_queries: descriptors/512_flickr_descriptor_val_q.h5

cirtorch:
  model_dir: model_dir
  img_resolution: 512

properties:
  gpu: 0
  output_dir: "output"