name: im2gps
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.7.*
  - pip
  - requests=2.24.0
  - mongoengine=0.20.0
  - pillow=8.0.1
  - pytables=3.6.1
  - pytorch=1.1.0
  - click=7.0
  - omegaconf=2.0.*
  - pyyaml
  - faiss-cpu
  - scipy
  - pip:
      - flickrapi == 2.4.0
      - haversine == 2.3.0
      - resources/cirtorch-0.0.1-py3-none-any.whl