name: im2gps
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7.*
  - pip
  - requests=2.24.0
  - mongoengine>=0.22.0
  - pillow=8.0.1
  - pytables=3.6.1
  - pytorch=1.8.0
  - click=7.0
  - omegaconf=2.0.*
  - pyyaml
  - faiss-cpu
  - scipy
  - jupyterlab
  - ipywidgets
  - pandas
  - seaborn
  - pytest
  - tqdm
  - scikit-learn
  - plotly
  - psutil
  - pip:
      - KDEpy
      - flickrapi == 2.4.0
      - haversine == 2.3.0
      - click-option-group
      - resources/cirtorch-0.0.1-py3-none-any.whl