db_config:
  db: ???
  host: ???
  port: ???
dataset_file: ???
test_dataset: ???
properties:
  results_dir: ???
  k: ???
  print_freq: ???
batch_size: ???
num_workers: ???
net_cfg_path: ???
gpu_id: ???