net_config_path: ???
optimizer_config:

scheduler_config:

data_config:
  db_config:
    db: ???
    host: ???
    port: ???
  train_ds: ???
  val_ds: ???
  batch_size: ???
  num_workers: ???
properties:
  base_dir: ???
  print_freq: ???
  sma_window: ???
  num_epochs: ???
  gpu_id: ???
  validate: ???
